use crate::endpoint;
use crate::middleware::jwt_middleware::JwtMiddleware;
use crate::middleware::login_governor::login_governor;
use actix_governor::Governor;
use actix_web::web;

pub fn configure(config: &mut web::ServiceConfig) {
    config.service(
        web::scope("/api")
            .service(
                web::resource("/auth/login")
                    .wrap(Governor::new(&login_governor()))
                    .post(endpoint::auth::login::post),
            )
            .service(web::resource("/auth/refresh").post(endpoint::auth::refresh::post))
            .service(web::resource("/auth/logout").post(endpoint::auth::logout::post))
            .service(web::resource("/users").post(endpoint::users::create::create))
            .service(
                web::scope("/users/me")
                    .wrap(JwtMiddleware)
                    .service(web::resource("").get(endpoint::users::me::get))
                    .service(web::resource("/username").patch(endpoint::users::username::patch))
                    .service(web::resource("/password").patch(endpoint::users::password::patch))
                    .service(web::resource("/email").patch(endpoint::users::email::patch))
                    .service(
                        web::resource("/notifications")
                            .patch(endpoint::users::notifications::patch),
                    ),
            )
            .service(
                web::scope("")
                    .wrap(JwtMiddleware)
                    .service(web::resource("/admin/digest").post(endpoint::admin::digest::post))
                    .service(web::resource("/invites").post(endpoint::invites::create::post))
                    .service(
                        web::scope("/projects")
                            .service(web::resource("/deadlines").get(endpoint::projects::deadlines::get::get))
                            .service(
                                web::resource("")
                                    .get(endpoint::projects::get::get)
                                    .post(endpoint::projects::create::create),
                            )
                            .service(
                                web::resource("/{project_id}")
                                    .delete(endpoint::projects::id::delete::delete),
                            )
                            .service(
                                web::resource("/{project_id}/title")
                                    .patch(endpoint::projects::id::rename::patch),
                            )
                            .service(
                                web::resource("/{project_id}/stages")
                                    .get(endpoint::projects::id::stages::get::get)
                                    .post(endpoint::projects::id::stages::create::create),
                            )
                            .service(
                                web::resource("/{project_id}/stages/{stage_id}")
                                    .post(endpoint::projects::id::stages::position::create::create)
                                    .get(endpoint::projects::id::stages::position::get::get)
                                    .delete(endpoint::projects::id::stages::position::delete::delete),
                            )
                            .service(
                                web::resource("/{project_id}/stages/{stage_id}/title")
                                    .patch(endpoint::projects::id::stages::position::title::patch),
                            )
                            .service(
                                web::resource("/{project_id}/stages/{stage_id}/deadline")
                                    .patch(endpoint::projects::id::stages::position::deadline::patch),
                            )
                            .service(
                                web::resource("/{project_id}/stages/{stage_id}/description")
                                    .patch(endpoint::projects::id::stages::position::description::patch),
                            )
                            .service(
                                web::resource("/{project_id}/stages/{stage_id}/cost")
                                    .patch(endpoint::projects::id::stages::position::cost::patch),
                            )
                            .service(
                                web::resource("/{project_id}/stages/{stage_id}/completed")
                                    .patch(endpoint::projects::id::stages::position::completed::patch),
                            )
                            .service(
                                web::resource("/{project_id}/stages/{stage_id}/attachments")
                                    .get(endpoint::projects::id::stages::position::attachments::list::get)
                                    .post(endpoint::projects::id::stages::position::attachments::upload::post),
                            )
                            .service(
                                web::resource("/{project_id}/stages/{stage_id}/attachments/{attachment_id}/download")
                                    .get(endpoint::projects::id::stages::position::attachments::download::get),
                            )
                            .service(
                                web::resource("/{project_id}/stages/{stage_id}/attachments/{attachment_id}")
                                    .delete(endpoint::projects::id::stages::position::attachments::delete::delete),
                            ),
                    ),
            ),
    );
}
